export const homeObjOne = {
  id: "aboutus",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "About Us",
  headline: "We are a student-run club from Coppell High School",
  description: "Here to help solve problems using AI",
  buttonLabel: "Contact Us",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "schedule",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Schedule",
  headline: "We are a student-run club from Coppell High School",
  description: "Here to help solve problems using AI",
  buttonLabel: "Join Now",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
};
export const homeObjThree = {
  id: "faq",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "FAQ",
  headline: "We are a student-run club from Coppell High School",
  description: "Here to help solve problems using AI",
  buttonLabel: "Contact Us",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFour = {
  id: "contactus",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Contact Us",
  headline: "We are a student-run club from Coppell High School",
  description: "Here to help solve problems using AI",
  buttonLabel: "Contact Us",
  imgStart: true,
  img: require("../../images/svg-4.svg").default,
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
};
